### ISSUE TITLE
Null error using 1.17.1

### ISSUE THREAD

**Issue by OrsoSgravato34** [wargamer/SignShop#167]
here's the full error log

`[SignShop] Enabling SignShop v4.0.0
[03:17:33 ERROR]: Error occurred while enabling SignShop v4.0.0 (Is it up to date?)
java.lang.NoSuchMethodError: 'org.bukkit.configuration.MemoryConfigurationOptions org.bukkit.configuration.file.FileConfigurationOptions.parseComments(boolean)'
        at org.wargamer2010.signshop.configuration.configUtil.loadYMLFromJar(configUtil.java:193) ~[SignShop-4.0.0.jar:?]
        at org.wargamer2010.signshop.configuration.configUtil.loadYMLFromJar(configUtil.java:183) ~[SignShop-4.0.0.jar:?]
        at org.wargamer2010.signshop.configuration.SignShopConfig.initConfig(SignShopConfig.java:225) ~[SignShop-4.0.0.jar:?]
        at org.wargamer2010.signshop.configuration.SignShopConfig.init(SignShopConfig.java:109) ~[SignShop-4.0.0.jar:?]
        at org.wargamer2010.signshop.configuration.SignShopConfig.<init>(SignShopConfig.java:95) ~[SignShop-4.0.0.jar:?]
        at org.wargamer2010.signshop.SignShop.onEnable(SignShop.java:153) ~[SignShop-4.0.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[03:17:33 INFO]: [SignShop] Disabling SignShop v4.0.0
[03:17:33 ERROR]: Error occurred while disabling SignShop v4.0.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.wargamer2010.signshop.configuration.FileSaveWorker.stop()" because "org.wargamer2010.signshop.configuration.Storage.fileSaveWorker" is null
        at org.wargamer2010.signshop.configuration.Storage.dispose(Storage.java:86) ~[SignShop-4.0.0.jar:?]
        at org.wargamer2010.signshop.SignShop.onDisable(SignShop.java:277) ~[SignShop-4.0.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Comment by weaves7** [comment]
Signshop v4 was built for Minecraft 1.20, you need to use [Signshop v3](https://www.spigotmc.org/resources/signshop.10997/download?version=484202) for Minecraft 1.13-1.19.
