### ISSUE TITLE
Unable to set up chests containing potions correctly

### ISSUE THREAD

**Issue by watadora** [wargamer/SignShop#168]
When our server update to Minecraft 1.21.1, we cannot sell or buy chests containing potions. Specifically, if I left-click on a chest containing potions with redstone dust, the chest will break. Additionally, nothing is displayed in the Minecraft chat log when this happens. (Normally, I would see “[SignShop] Stored location of Chest containing ...” in the chat log.)

Instead, the following error appears in the console:

```
[15:15:01 ERROR]: Could not pass event PlayerInteractEvent to SignShop v4.0.0
java.lang.NoSuchFieldError: Class org.bukkit.potion.PotionType does not have member field 'org.bukkit.potion.PotionType UNCRAFTABLE'
        at SignShop-4.0.0.jar/org.wargamer2010.signshop.blocks.SignShopItemMeta.getName(SignShopItemMeta.java:159) ~[SignShop-4.0.0.jar:?]
        at SignShop-4.0.0.jar/org.wargamer2010.signshop.util.itemUtil.itemStackToString(itemUtil.java:249) ~[SignShop-4.0.0.jar:?]
        at SignShop-4.0.0.jar/org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:454) ~[SignShop-4.0.0.jar:?]
        at SignShop-4.0.0.jar/org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:430) ~[SignShop-4.0.0.jar:?]
        at SignShop-4.0.0.jar/org.wargamer2010.signshop.util.signshopUtil.registerClickedMaterial(signshopUtil.java:425) ~[SignShop-4.0.0.jar:?]
        at SignShop-4.0.0.jar/org.wargamer2010.signshop.listeners.SignShopPlayerListener.onPlayerInteract(SignShopPlayerListener.java:242) ~[SignShop-4.0.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor73.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-122-4430e96]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:560) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:555) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:204) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1856) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

This issue does not occur with items other than potions. A likely cause Iguess is a change in the "org.bukkit.potion.PotionType" API, which prevents the detection of potion types correctly. Could you please fix this bug?

The versions we are using are:
- Paper-1.21.1, Build 122
- Vault 1.7.3

**Comment by weaves7** [comment]
Here is a dev build that should take care of it, its on the Discord https://discord.com/channels/688544126521704455/704502032610099290

https://cdn.discordapp.com/attachments/704502032610099290/1266868831645601892/SignShop-5.0.0-dev.jar?ex=670d8c0a&is=670c3a8a&hm=a6fb302c71f3cc2040023498540e86ebad3e84b1270351c14570475e489768ff&

**Comment by watadora** [comment]
Thank you so much! I couldn’t access the channel link since I'm not in that Discord server, but download link worked, so I downloaded it.
We quickly checked its operation and confirmed that it works without any issues, including other functions. I’m looking forward to the official release of v5.0.0 as well. Thank you!
