### ISSUE TITLE
i can not buy/ sell items.

### ISSUE THREAD

**Issue by lawantemouze** [wargamer/SignShop#98]
i have installed sighnshop and vault in my server to make a shop. i used the redstone as described in the basic tutorial. only when i try to sell/buy items from the signs it says;

"you are overstocked, either your inventory is to full, or you can not hold any more money."

how do i fix this problem
![Knipsel](https://user-images.githubusercontent.com/71836107/94162998-a033a280-fe87-11ea-9034-a66e488dee27.PNG)
![Knipsel](https://user-images.githubusercontent.com/71836107/94163082-b7729000-fe87-11ea-8d08-d34879615c6b.PNG)

**Comment by weaves7** [comment]
Pastebin your startup log.

**Comment by lawantemouze** [comment]
[17:26:12] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[17:26:13] [main/INFO]: Reloading ResourceManager: Default, bukkit
[17:26:14] [Server-Worker-11/INFO]: Loaded 7 recipes
[17:26:16] [Server thread/INFO]: Starting minecraft server version 1.16.1
[17:26:16] [Server thread/INFO]: Loading properties
[17:26:16] [Server thread/INFO]: This server is running Paper version git-Paper-47 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[17:26:16] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:26:16] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:26:16] [Server thread/INFO]: Debug logging is disabled
[17:26:17] [Server thread/INFO]: Default game type: SURVIVAL
[17:26:17] [Server thread/INFO]: Generating keypair
[17:26:17] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25574
[17:26:17] [Server thread/INFO]: Using epoll channel type
[17:26:17] [Server thread/ERROR]: Could not load 'plugins/craftbukkit-1.16.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.1.jar:git-Paper-47]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.1.jar:git-Paper-47]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-47]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-47]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-47]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-47]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 7 more
[17:26:18] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[17:26:25] [Server thread/WARN]: Legacy plugin Warp v1.1 does not specify an api-version.
[17:26:25] [Server thread/INFO]: [Warp] Loading Warp v1.1
[17:26:25] [Server thread/INFO]: [HomePlus] Loading HomePlus v3.9.6
[17:26:25] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v7.1.0;8e55131
[17:26:26] [Server thread/INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@46b7a0c4]
[17:26:26] [Server thread/INFO]: [mcMMO] Loading mcMMO v2.1.145
[17:26:26] [Server thread/INFO]: [Vault] Loading Vault v1.7.3-b131
[17:26:26] [Server thread/INFO]: [SignShop] Loading SignShop v3.5.0
[17:26:26] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:26:26] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v7.1.0;8e55131
[17:26:26] [Server thread/WARN]: [WorldEdit] Loaded class net.milkbowl.vault.permission.Permission from Vault v1.7.3-b131 which is not a depend, softdepend or loadbefore of this plugin.
[17:26:26] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[17:26:27] [Server thread/WARN]: 
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and block property-related functions.
**
** Please see https://worldedit.enginehub.org/en/latest/faq/#bukkit-adapters
**********************************************

[17:26:27] [Server thread/INFO]: [Vault] Enabling Vault v1.7.3-b131
[17:26:27] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[17:26:27] [Server thread/INFO]: [Vault] Enabled Version 1.7.3-b131
[17:26:27] [Server thread/INFO]: WEPIF: Vault detected! Using Vault for permissions
[17:26:27] [Server thread/INFO]: Preparing level "world"
[17:26:27] [Server thread/INFO]: -------- World Settings For [world] --------
[17:26:27] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:26:27] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Carrot Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Potato Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Vine Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Kelp Growth Modifier: 100%
[17:26:27] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[17:26:27] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[17:26:27] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[17:26:27] [Server thread/INFO]: Max TNT Explosions: 100
[17:26:27] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:26:27] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:26:27] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:26:27] [Server thread/INFO]: Item Merge Radius: 2.5
[17:26:27] [Server thread/INFO]: Item Despawn Rate: 6000
[17:26:27] [Server thread/INFO]: View Distance: 10
[17:26:27] [Server thread/INFO]: Mob Spawn Range: 6
[17:26:27] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[17:26:27] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:26:27] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:26:28] [Server thread/INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[17:26:28] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[17:26:28] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:26:28] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Carrot Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Potato Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Vine Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Kelp Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[17:26:28] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[17:26:28] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[17:26:28] [Server thread/INFO]: Max TNT Explosions: 100
[17:26:28] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:26:28] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:26:28] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:26:28] [Server thread/INFO]: Item Merge Radius: 2.5
[17:26:28] [Server thread/INFO]: Item Despawn Rate: 6000
[17:26:28] [Server thread/INFO]: View Distance: 10
[17:26:28] [Server thread/INFO]: Mob Spawn Range: 6
[17:26:28] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[17:26:28] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:26:28] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:26:28] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[17:26:28] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:26:28] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Beetroot Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Carrot Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Potato Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Vine Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Bamboo Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: SweetBerry Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Kelp Growth Modifier: 100%
[17:26:28] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
[17:26:28] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[17:26:28] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
[17:26:28] [Server thread/INFO]: Max TNT Explosions: 100
[17:26:28] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:26:28] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:26:28] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:26:28] [Server thread/INFO]: Item Merge Radius: 2.5
[17:26:28] [Server thread/INFO]: Item Despawn Rate: 6000
[17:26:28] [Server thread/INFO]: View Distance: 10
[17:26:28] [Server thread/INFO]: Mob Spawn Range: 6
[17:26:28] [Server thread/INFO]: Arrow Despawn Rate: 1200 Trident Respawn Rate:1200
[17:26:28] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:26:28] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:26:28] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:26:29] [Server thread/INFO]: Loaded 0 spawn chunks for world world
[17:26:29] [Server thread/INFO]: Preparing spawn area: 0%
[17:26:29] [Server thread/INFO]: Preparing spawn area: 0%
[17:26:29] [Server thread/INFO]: Preparing spawn area: 0%
[17:26:30] [Server thread/INFO]: Preparing spawn area: 0%
[17:26:30] [Server thread/INFO]: Time elapsed: 1913 ms
[17:26:30] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[17:26:30] [Server thread/INFO]: Loaded 0 spawn chunks for world world_nether
[17:26:30] [Server thread/INFO]: Preparing spawn area: 0%
[17:26:31] [Server thread/INFO]: Preparing spawn area: 0%
[17:26:31] [Server thread/INFO]: Time elapsed: 567 ms
[17:26:31] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[17:26:31] [Server thread/INFO]: Loaded 0 spawn chunks for world world_the_end
[17:26:32] [Server thread/INFO]: Time elapsed: 1423 ms
[17:26:32] [Server thread/INFO]: [Warp] Enabling Warp v1.1*
[17:26:32] [Server thread/INFO]: [HomePlus] Enabling HomePlus v3.9.6
[17:26:32] [Server thread/INFO]: 
[17:26:32] [Server thread/INFO]: 
[17:26:32] [Server thread/INFO]:      ___   ___   ______    
[17:26:32] [Server thread/INFO]:     /__/\ /__/\ /_____/\   
[17:26:32] [Server thread/INFO]:     \::\ \\  \ \\:::_ \ \  
[17:26:32] [Server thread/INFO]:      \::\/_\ .\ \\:(_) \ \ 
[17:26:32] [Server thread/INFO]:       \:: ___::\ \\: ___\/ 
[17:26:32] [Server thread/INFO]:        \: \ \\::\ \\ \ \   
[17:26:32] [Server thread/INFO]:         \__\/ \::\/ \_\/   
[17:26:32] [Server thread/INFO]: 
[17:26:32] [Server thread/INFO]: Status: Enabled Successfully
[17:26:32] [Server thread/INFO]: Version: 3.9.6
[17:26:32] [Server thread/INFO]: Compatible with: 1.9 - 1.16
[17:26:32] [Server thread/INFO]: Native MVersion: 1.16.1
[17:26:32] [Server thread/INFO]: HPVersion: Pre-Release
[17:26:32] [Server thread/INFO]: bStats: Enabled
[17:26:32] [Server thread/INFO]: Author: _peppeee24_
[17:26:32] [Server thread/INFO]: 
[17:26:32] [Server thread/INFO]: (!) Don't forget to rate this plugin 5 STARS!! (!)
[17:26:32] [Server thread/INFO]: 
[17:26:32] [Server thread/INFO]: [mcMMO] Enabling mcMMO v2.1.145
[17:26:33] [Server thread/INFO]: [mcMMO] Platform String: 1.16.1-R0.1-SNAPSHOT
[17:26:33] [Server thread/INFO]: [mcMMO] Minecraft version determined to be - 1.16.1
[17:26:33] [Server thread/INFO]: [mcMMO] Loading compatibility layers...
[17:26:33] [Server thread/INFO]: [mcMMO] Finished loading compatibility layers.
[17:26:35] [Server thread/INFO]: [mcMMO] Enabling Acrobatics Skills
[17:26:35] [Server thread/INFO]: [mcMMO] Registered subskill: Roll
[17:26:35] [Server thread/INFO]: [mcMMO] 0 entries in mcMMO World Blacklist
[17:26:35] [Server thread/INFO]: [SignShop] Enabling SignShop v3.5.0
[17:26:35] [Server thread/INFO]: [SignShop] Checking data version.
[17:26:35] [Server thread/INFO]: [SignShop] Your data is current.
[17:26:37] [Server thread/INFO]: [SignShop] Vault's permissions not found, defaulting to OP.
[17:26:37] [Server thread/WARN]: [SignShop] Could not hook into Vault's Economy!
[17:26:37] [Server thread/WARN]: [SignShop] No compatible worth plugin found, [Worth] disabled.
[17:26:37] [Server thread/INFO]: [SignShop] Thank you for enabling metrics!
[17:26:37] [Server thread/INFO]: [SignShop] v3.5.0 Enabled
[17:26:37] [Server thread/INFO]: Running delayed init tasks
[17:26:37] [Server thread/INFO]: Done (21.568s)! For help, type "help"
[17:26:37] [Server thread/INFO]: Timings Reset
[17:26:38] [Craft Scheduler Thread - 2/INFO]: [mcMMO] Cleaned backup files. Deleted 2 of 7 files.
[17:26:38] [Craft Scheduler Thread - 4/INFO]: [Vault] Checking for Updates ... 
[17:26:38] [Craft Scheduler Thread - 3/INFO]: (HomePlus) Checking for new Updates....
[17:26:38] [Craft Scheduler Thread - 3/INFO]: (HomePlus) Perfect! You are using the latest version of the plugin!
[17:26:38] [Craft Scheduler Thread - 4/INFO]: [Vault] No new version available
[17:27:14] [Server thread/INFO]: There are 0 of a max of 24 players online:

**Comment by weaves7** [comment]
You need a vault compatible economy plugin.
